name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


       # Set AWS credentials from GitHub Secrets key
      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY    



      - name: Pull DVC data
        run: |
          dvc pull --force  # Pull the data from remote storage


      - name: Run pipeline
        env:
         DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro
      - name: Run test
        env:
         DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
         python -m unittest test/test_model.py 

